Repository F5Networks/f5-openstack-lbaasv2-driver, pull requests merged in 2020-11, with the labels that each got.

#1027 Create v112.5.0 release
  f5lbaasdriver/__init__.py
Labels: prerelease

#1028 Revert "fix bug: delete lb will delete route domain and partition."
  f5lbaasdriver/v2/bigip/driver_v2.py
  f5lbaasdriver/v2/bigip/test/test_driver_v2.py
Labels: bug

#1029 Revert "Merge pull request #994 from zhang-shengping/h3c-pike-delete-lb-fix"
  f5lbaasdriver/v2/bigip/driver_v2.py
Labels: bug

#1031 Revert "fix bug: delete lb will delete route domain and partition."
  f5lbaasdriver/v2/bigip/driver_v2.py
  f5lbaasdriver/v2/bigip/test/test_driver_v2.py
Labels: bug

#1032 change for route domain
  f5lbaasdriver/v2/bigip/service_builder.py
Labels: enhancement

#1033 Create 112.5.1 release
  f5lbaasdriver/__init__.py
Labels: prerelease

#1035 avoid getting lb from db without modifying prototype of schedule
  f5lbaasdriver/v2/bigip/agent_scheduler.py
Labels: enhancement

#1039 avoid getting lb from db
  f5lbaasdriver/v2/bigip/agent_scheduler.py
Labels: enhancement

#1038 avoid getting lb from db
  f5lbaasdriver/v2/bigip/agent_scheduler.py
Labels: enhancement

#1040 cherry pick qos driver code change to F5 driver stable/queens
  f5lbaasdriver/v2/bigip/service_builder.py
Labels: bug
